version: 0.2

env:
  variables:
    FLASK_APP: app.py
    FLASK_ENV: production

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Upgrade pip and install dependencies
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install gunicorn

  pre_build:
    commands:
      # Any preparation steps you need can go here
      - echo Pre-build phase complete.

  build:
    commands:
      # Building your app for deployment
      - echo Building your Flask app...
      - python -m flask --app $FLASK_APP db init  # Optional: if you need to initialize a database

  post_build:
    commands:
      - echo Build complete, ready to deploy!
      # Ensure your app starts with gunicorn for production (or you could use flask run, depending on your setup)
      - gunicorn --bind 0.0.0.0:5000 app:app

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: .
