version: 0.2

env:
  variables:
    FLASK_APP: app.py
    FLASK_ENV: production
    PORT: 8080

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install gunicorn

  pre_build:
    commands:
      - echo Pre-build phase complete.

  build:
    commands:
      - echo Building your Flask app...
      # Removed 'flask db init' to avoid errors

  post_build:
    commands:
      - echo Build complete, ready to deploy!
      - gunicorn --bind 0.0.0.0:8080 app:app  # Match Dockerfile port

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: .
