version: 0.2

env:
  variables:
    FLASK_APP: app.py
    FLASK_ENV: production
    PORT: 8080

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install gunicorn  # For when deploying with Elastic Beanstalk

  pre_build:
    commands:
      - echo Pre-build phase complete.

  build:
    commands:
      - echo Building your Flask app...
      # Add additional build commands here if needed, e.g., to run tests
      # - pytest  # Example: run tests

  post_build:
    commands:
      - echo Build complete, ready to deploy!

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: .
