name: Deploy to EC2 with Amazon ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1                # Set to your AWS region
  ECR_REPOSITORY: studentperformance   # Your ECR repository name
  EC2_PUBLIC_IP: 54.90.169.53          # Replace with your EC2 instance's public IP
  SSH_KEY: ${{ secrets.EC2_SSH_KEY }}  # SSH key stored in GitHub secrets
  EC2_USER: ec2-user                   # Default user for Amazon Linux

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

    - name: Deploy to EC2
      run: |
        echo "$SSH_KEY" > private_key.pem
        chmod 600 private_key.pem

        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_PUBLIC_IP << 'EOF'
          echo "Pulling latest Docker image..."
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
          docker pull $IMAGE
          
          echo "Stopping and removing old container..."
          docker stop studentperformance || true
          docker rm studentperformance || true

          echo "Running new container..."
          docker run -d -p 5000:5000 --name studentperformance $IMAGE
        EOF

        rm -f private_key.pem
