name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

env:
  AWS_REGION: us-east-1                      # Replace with your AWS region
  ECR_REPOSITORY: studentperformance         # Replace with your Amazon ECR repository name
  EC2_PUBLIC_IP: 54.90.169.53                # Replace with your actual EC2 Public IP
  EC2_USER: ubuntu                           # Amazon Linux uses 'ec2-user', Ubuntu uses 'ubuntu'

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag, and Push Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

    - name: Create and Convert Private Key to PEM
      run: |
        # Restore SSH private key and convert to PEM format
        echo "${{ secrets.EC2_SSH_KEY }}" | sed 's/\\n/\n/g' > private_key.pem
        chmod 600 private_key.pem
        
        # Ensure key is in PEM format (for OpenSSH compatibility)
        ssh-keygen -p -m PEM -f private_key.pem -N "" || true

    - name: Debug SSH Connection
      run: |
        echo "Testing SSH connection..."
        ssh -v -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@${{ env.EC2_PUBLIC_IP }} "echo SSH Connected!"

    - name: Deploy to EC2
      run: |
        ssh -tt -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@${{ env.EC2_PUBLIC_IP }} << 'EOF'
          echo "✅ Successfully connected to EC2!"
          echo "Pulling Docker image from Amazon ECR..."
          docker pull $IMAGE
          
          echo "Stopping old container (if any)..."
          docker stop my-python-app || true
          
          echo "Removing old container (if any)..."
          docker rm my-python-app || true
          
          echo "Running new Docker container..."
          docker run -d -p 5000:5000 --name my-python-app $IMAGE
          
          echo "✅ Deployment complete!"
          exit
        EOF
